version: "3"

services:
  blockchain:
    container_name: blockchain-server
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "air -c /app/go/base/cmd/.air.toml"
    env_file:
      - .env
    image: blockchain
    volumes:
      - .:/app/go/base:rw
    tty: true
    ports:
      - ${REST_PORT}:${REST_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
